# Generated by Django 6.0.7 on 2026-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название автомобиля')),
                ('car_class', models.CharField(choices=[('Эконом', 'Эконом'), ('Комфорт', 'Комфорт'), ('Бизнес', 'Бизнес'), ('Внедорожник', 'Внедорожник'), ('Премиум', 'Премиум')], max_length=30, verbose_name='Класс автомобиля')),
                ('plate', models.CharField(max_length=20, verbose_name='Государственный номер')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за сутки ($)')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('gearbox', models.CharField(max_length=100, verbose_name='Коробка передач')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('fuel', models.CharField(max_length=50, verbose_name='Тип топлива')),
                ('consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото автомобиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['id'],
            },
        ),
    ]
