# Generated by Django 6.0.7 on 2026-07-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата начала брони')),
                ('date_to', models.DateField(verbose_name='Дата окончания брони')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['car', 'date_from'],
            },
        ),
    ]
